version: "3"

services:   
    tika:
        container_name: tika
        image: "apache/tika:1.24-full"
        ports:
            - "9998:9998"

    flask:
        build: .
        container_name: flask
        ports:
            - "5001:5000"
        volumes: 
            - ./app:/app
        depends_on: 
            - tika

    nlp:
        container_name: nlp
        image: jgontrum/spacyapi:en_v2
        ports:
            - "8100:8000"
        restart: always
        depends_on:
            - tika

    speech_recognition:
        build: ./app/speech
        container_name: speech_recognition
        ports:
            - '8001:8001'
        restart: 'unless-stopped'
        volumes:
            - './model.pbmm:/app/model.pbmm:ro'
        depends_on:
            - tika

    captioning:
        build: ./app/captioning
        container_name: caption
        ports:
            - "5500:5000"
        depends_on: 
            - tika

    classification:
        build: ./app/classification
        container_name: classification
        ports:
            - "5050:5000"
        depends_on: 
            - tika
