version: "3"

services:   
    tika:
        container_name: tika
        image: "apache/tika:1.24-full"
        ports:
            - "9998:9998"

    flask:
        build: ./app/flask
        container_name: flask
        ports:
            - "5001:5000"
        volumes: 
            - ./app:/app
        depends_on: 
            - tika

    nlp:
        container_name: nlp
        image: jgontrum/spacyapi:en_v2
        ports:
            - "8100:8000"
        restart: always
        depends_on:
            - tika

    speech_recognition:
        build: ./app/speech
        container_name: speech_recognition
        ports:
            - '8001:8001'
        restart: 'unless-stopped'
        volumes:
        -   ../models:/models
        depends_on:
            - tika

    captioning:
        build: ./app/captioning
        container_name: caption
        ports:
            - "5500:5000"
        depends_on: 
            - tika
        volumes:
        -   ../models:/models

    classification:
        build: ./app/classification
        container_name: classification
        ports:
            - "5050:5000"
        depends_on: 
            - tika
        volumes:
        -   ../models:/models

    categorisation:
        build: ./app/categorisation
        container_name: categorisation
        ports:
            - "6060:5000"
        depends_on: 
            - classification
        volumes:
        -   ../models:/models

    language:
        build: ./app/language
        container_name: language
        ports:
            - "2468:5000"
        depends_on: 
            - tika

    video_object_recognition:
        build: ./app/video_or
        container_name: video_object_recognition
        ports:
            - "8181:5000"
        depends_on:
            - tika
        volumes:
        -   ../models:/models
