version: "3"

services:
    flask:
        build: ./flask
        container_name: flask
        ports:
            - "5001:5000"
        volumes: 
            - ./flask/app:/app
        depends_on: 
            - tika
    
    tika:
        container_name: tika
        image: "apache/tika:1.24-full"
        ports:
            - "9998:9998"
